---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# flippingtables

<!-- badges: start -->
<!-- badges: end -->

The goal of flippingtables is to ...

## Installation

You can install the development version of flippingtables from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("MilesMcBain/flippingtables")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(flippingtables)
library(palmerpenguins)

register_flips(
		printer_fns = list(
      paint::paint,
      pillar::glimpse,
      default_print),
		printed_classes = list(
			print_override(class = "tbl", pkg_namespace = "pillar"),
			print_override(class = "data.frame", pkg_namespace = "base"),
			print_override(class = "data.table", pkg_namespace = "data.table")
		)
	)
	flip_on()
	penguins

	flip()

	# it's sticky!
	penguins

	flip()

```

